[tools]
go = "1.25"
golangci-lint = "2"
lefthook = "latest"

[env]
OTEL_SERVICE_NAME = "u_go_trace"
# OTEL_EXPORTER_OTLP_ENDPOINT = "localhost:4317"
OTEL_EXPORTER_OTLP_ENDPOINT = "localhost:8080"

[tasks.go-generate]
description = "Generate BPF Go bindings using bpf2go"
run = "go generate ./internal/bpf"

[tasks.go-build]
description = "Build Go process-tracer binary"
run = "go build -o process-tracer ./cmd/process-tracer"
depends = ["go-generate"]

[tasks.go-clean]
description = "Clean generated Go files and binary"
run = "rm -f process-tracer internal/bpf/processtracer_*.go internal/bpf/processtracer_*.o"

[tasks.setcap]
description = "Set capabilities on process-tracer binary to run without sudo"
run = "sudo setcap cap_bpf,cap_perfmon,cap_net_admin,cap_sys_resource,cap_dac_override+ep ./process-tracer"
depends = ["go-build"]

[tasks.lint]
description = "Run golangci-lint on the codebase"
run = "golangci-lint run ./..."

[tasks.lint-fix]
description = "Run golangci-lint and auto-fix issues where possible"
run = "golangci-lint run --fix ./..."
