[tools]
go = "1.25"

[env]
OTEL_SERVICE_NAME = "u_go_trace"
# OTEL_EXPORTER_OTLP_ENDPOINT = "localhost:4317"
OTEL_EXPORTER_OTLP_ENDPOINT = "localhost:8080"

[tasks.go-generate]
description = "Generate BPF Go bindings using bpf2go"
run = "go generate ./internal/bpf"

[tasks.go-build]
description = "Build Go sched_trace binary"
run = "go build -o sched_trace ./cmd/sched_trace"
depends = ["go-generate"]

[tasks.go-clean]
description = "Clean generated Go files and binary"
run = "rm -f sched_trace internal/bpf/schedtrace_*.go internal/bpf/schedtrace_*.o"

[tasks.setcap]
description = "Set capabilities on sched_trace binary to run without sudo"
run = "sudo setcap cap_bpf,cap_perfmon,cap_net_admin,cap_sys_resource,cap_dac_override+ep ./sched_trace"
depends = ["go-build"]
