// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type processTracerEnvStreamState struct {
	_             structs.HostLayout
	ArgvPtr       uint64
	EnvpPtr       uint64
	VarIndex      uint16
	Argc          uint16
	ProcessingEnv uint8
	Pad           [3]uint8
	Timestamp     uint64
	Ppid          uint32
	Uid           uint32
}

type processTracerTcpSpanInfo struct {
	_         structs.HostLayout
	StartTime uint64
	Pid       uint32
	Family    uint16
	_         [2]byte
}

// loadProcessTracer returns the embedded CollectionSpec for processTracer.
func loadProcessTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProcessTracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load processTracer: %w", err)
	}

	return spec, err
}

// loadProcessTracerObjects loads processTracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*processTracerObjects
//	*processTracerPrograms
//	*processTracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProcessTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProcessTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// processTracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processTracerSpecs struct {
	processTracerProgramSpecs
	processTracerMapSpecs
	processTracerVariableSpecs
}

// processTracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processTracerProgramSpecs struct {
	HandleExec             *ebpf.ProgramSpec `ebpf:"handle_exec"`
	HandleExit             *ebpf.ProgramSpec `ebpf:"handle_exit"`
	HandleInetSockSetState *ebpf.ProgramSpec `ebpf:"handle_inet_sock_set_state"`
	TcpV4ConnectEntry      *ebpf.ProgramSpec `ebpf:"tcp_v4_connect_entry"`
	TcpV4ConnectExit       *ebpf.ProgramSpec `ebpf:"tcp_v4_connect_exit"`
	TcpV6ConnectEntry      *ebpf.ProgramSpec `ebpf:"tcp_v6_connect_entry"`
	TcpV6ConnectExit       *ebpf.ProgramSpec `ebpf:"tcp_v6_connect_exit"`
	TraceExecveEnter       *ebpf.ProgramSpec `ebpf:"trace_execve_enter"`
}

// processTracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processTracerMapSpecs struct {
	ActiveTcpConns    *ebpf.MapSpec `ebpf:"active_tcp_conns"`
	EnvStreamStateMap *ebpf.MapSpec `ebpf:"env_stream_state_map"`
	EnvVarBuffer      *ebpf.MapSpec `ebpf:"env_var_buffer"`
	InflightConnects  *ebpf.MapSpec `ebpf:"inflight_connects"`
	InflightExecve    *ebpf.MapSpec `ebpf:"inflight_execve"`
	ProgArray         *ebpf.MapSpec `ebpf:"prog_array"`
	Rb                *ebpf.MapSpec `ebpf:"rb"`
	TrackedPids       *ebpf.MapSpec `ebpf:"tracked_pids"`
}

// processTracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processTracerVariableSpecs struct {
	AmbientMode *ebpf.VariableSpec `ebpf:"ambient_mode"`
}

// processTracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProcessTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type processTracerObjects struct {
	processTracerPrograms
	processTracerMaps
	processTracerVariables
}

func (o *processTracerObjects) Close() error {
	return _ProcessTracerClose(
		&o.processTracerPrograms,
		&o.processTracerMaps,
	)
}

// processTracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProcessTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type processTracerMaps struct {
	ActiveTcpConns    *ebpf.Map `ebpf:"active_tcp_conns"`
	EnvStreamStateMap *ebpf.Map `ebpf:"env_stream_state_map"`
	EnvVarBuffer      *ebpf.Map `ebpf:"env_var_buffer"`
	InflightConnects  *ebpf.Map `ebpf:"inflight_connects"`
	InflightExecve    *ebpf.Map `ebpf:"inflight_execve"`
	ProgArray         *ebpf.Map `ebpf:"prog_array"`
	Rb                *ebpf.Map `ebpf:"rb"`
	TrackedPids       *ebpf.Map `ebpf:"tracked_pids"`
}

func (m *processTracerMaps) Close() error {
	return _ProcessTracerClose(
		m.ActiveTcpConns,
		m.EnvStreamStateMap,
		m.EnvVarBuffer,
		m.InflightConnects,
		m.InflightExecve,
		m.ProgArray,
		m.Rb,
		m.TrackedPids,
	)
}

// processTracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProcessTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type processTracerVariables struct {
	AmbientMode *ebpf.Variable `ebpf:"ambient_mode"`
}

// processTracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProcessTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type processTracerPrograms struct {
	HandleExec             *ebpf.Program `ebpf:"handle_exec"`
	HandleExit             *ebpf.Program `ebpf:"handle_exit"`
	HandleInetSockSetState *ebpf.Program `ebpf:"handle_inet_sock_set_state"`
	TcpV4ConnectEntry      *ebpf.Program `ebpf:"tcp_v4_connect_entry"`
	TcpV4ConnectExit       *ebpf.Program `ebpf:"tcp_v4_connect_exit"`
	TcpV6ConnectEntry      *ebpf.Program `ebpf:"tcp_v6_connect_entry"`
	TcpV6ConnectExit       *ebpf.Program `ebpf:"tcp_v6_connect_exit"`
	TraceExecveEnter       *ebpf.Program `ebpf:"trace_execve_enter"`
}

func (p *processTracerPrograms) Close() error {
	return _ProcessTracerClose(
		p.HandleExec,
		p.HandleExit,
		p.HandleInetSockSetState,
		p.TcpV4ConnectEntry,
		p.TcpV4ConnectExit,
		p.TcpV6ConnectEntry,
		p.TcpV6ConnectExit,
		p.TraceExecveEnter,
	)
}

func _ProcessTracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed processtracer_x86_bpfel.o
var _ProcessTracerBytes []byte
